version: '3'

services:
  python:
    build: .
    container_name: merossApi
    network_mode: bridge
    restart: always
    hostname: merossapi-dck

    environment:
      - LANG=C.UTF-8
      - PYTHON_PIP_VERSION=22.3.1
      - PYTHON_VERSION=3.11.3

    ports:
      - '4449:4449'

    volumes:
      - '.:/usr/src/app'

volumes:
  merossApi_data:
    driver: local