version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: merossJS
    ports:
    - '8389:80'
    volumes:
    - './merossJS/dist/meross-js:/usr/local/apache2/htdocs'

version: '3'

